### ISSUE TITLE
Ability to edit remote files

### ISSUE THREAD

**Issue by dspasicpdy** [legat1/SftpPlugin#1]
Hi, 
It would be very effective if one could browse remote server via sftp - and be able to edit remote files.

example: CMD+SHIFT+P > open with editor > edit in editor > save > profit :D 

thought: _remote file should be duplicated on the local host, and upon saving - it should overwrite the remote/original file.._ 

How plausible is this? Thanks!

**Comment by blegat1** [comment]
Hi,
thanks for this effective suggestion.
I added it, enjoy :D

**Comment by dspasicpdy** [comment]
Hi,
Thank you a lot for quick reaction!
it works as described above.

_i use sftp plugin for sublime, but browsing remote files is not even 5% comfortable like in fman or mc, (file managing topic is out of scope here..) but the remote file handling is soo smooth.._

Thank you once again for quick reaction :)
