### ISSUE TITLE
issue with ssh config

### ISSUE THREAD

**Issue by dspasicpdy** [legat1/SftpPlugin#2]
Hi, 

1) when i have ssh config where i utilize only ssh keys i always get prompt for password upon initiating connection. 
If i set empty, it says 'connection error'. If i type random, it connects... 
    - if password is not needed - i should not be asked to type 'something' 

2) if the ssh user for certain host is not specified in ssh config, which user is being invoked? can this be changed/overriden somehow (apart from ssh config?)
    - ability to change ssh user (before initiating connection) would be great

Thanks!

**Comment by blegat1** [comment]
Hi,
1. my bad, I use identity file key to connect or user / password and I don't see this bug with public key. I fixed it.
2. I fixed it. Now if user is not specified in ssh config then you will get prompt to enter it.
Thanks for your feedbacks.

**Comment by dspasicpdy** [comment]
thank you a lot! i appreciate your efforts! :)
